---
- name: Master Only Setup Continue
  hosts: masters
  become: true

  tasks:
  - name: Copy script files
    copy:
      src:  ./scripts/master_only.sh
      dest: /tmp/script/
      owner: root
      group: root
      mode: 0777
         
  - name: Run script and save log
    shell: ./master_only.sh>>setup_masteronly.log
    args:
      chdir: /tmp/script/
      creates: setup_masteronly.log

  - name: Delete the script after execution
    file:
      path: /tmp/script/master_only.sh
      state: absent

